name: Test Formula

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04-arm
            label: linux arm
          - os: ubuntu-latest
            label: linux intel
          - os: macos-latest
            label: macos arm
          - os: macos-13
            label: macos intel

    steps:
    - uses: actions/checkout@v5

    - name: Show platform
      run: uname -a

    # https://github.com/Homebrew/actions/issues/742
    - name: Preinstall homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@main

    - name: Test formula syntax
      run: brew audit --strict --online kagent

    - name: Test formula installation
      run:  brew install --build-from-source kagent

    #   fails due to https://github.com/kagent-dev/kagent/issues/868
    # - name: Brew Test
    #   run: brew test kagent --verbose --debug

    - name: Test kagent binary
      run: kagent version || true

    - name: Test formula uninstall
      run: brew uninstall kagent
