name: Test Formula

on:
  pull_request:
    branches: [ main ]

jobs:
  # test-linux-arm:
  #   runs-on: ubuntu-22.04-arm
  #   steps:
  #   - uses: actions/checkout@v5

  #   - name: Install brew
  #     run: |
  #       uname -a
  #       /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  #       brew audit --strict --online kagent
  #       brew install --build-from-source kagent
  #       kagent version || true
  #       brew uninstall kagent

  test:
    name: test ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04-arm
            label: linux arm
          - os: ubuntu-latest
            label: linux amd64
          - os: macos-latest
            label: macos arm64
          - os: macos-13
            label: macos intel

    steps:
    - uses: actions/checkout@v5

    - name: Show platform
      run: uname -a

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@main

    - name: Test formula syntax
      run: brew audit --strict --online kagent

    - name: Test formula installation
      run:  brew install --build-from-source kagent

    - name: Test kagent binary
      run: kagent version || true

    - name: Test formula uninstall
      run: brew uninstall kagent
