name: Update Formula

on:
  push:
    branches:
      - main

jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write

    steps:
    - uses: actions/checkout@v5

    - name: Get current version ${{ env.VERSION}}
      id: version
      run: |
        echo "VERSION=$(curl -s "https://api.github.com/repos/kagent-dev/kagent/releases/latest" | jq -r .tag_name | sed 's/^v//')" >> $GITHUB_OUTPUT

    - name: Fetch release assets and SHAs
      id: fetch-assets
      run: |
        VERSION="${{ steps.version.outputs.VERSION }}"
        echo ":: Fetching release information for version $VERSION"
        RELEASE_INFO=$(curl -s "https://api.github.com/repos/kagent-dev/kagent/releases/tags/v${VERSION}")

        echo ":: Extracting SHA256 values from the digest field of each asset"
        DARWIN_ARM64_SHA=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name == "kagent-darwin-arm64") | .digest | split(":")[1]')
        DARWIN_AMD64_SHA=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name == "kagent-darwin-amd64") | .digest | split(":")[1]')
        LINUX_ARM64_SHA=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name == "kagent-linux-arm64") | .digest | split(":")[1]')
        LINUX_AMD64_SHA=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name == "kagent-linux-amd64") | .digest | split(":")[1]')

        echo ":: Setting outputs"
        echo "DARWIN_ARM64_SHA=$DARWIN_ARM64_SHA" >> $GITHUB_OUTPUT
        echo "DARWIN_AMD64_SHA=$DARWIN_AMD64_SHA" >> $GITHUB_OUTPUT
        echo "LINUX_ARM64_SHA=$LINUX_ARM64_SHA" >> $GITHUB_OUTPUT
        echo "LINUX_AMD64_SHA=$LINUX_AMD64_SHA" >> $GITHUB_OUTPUT

    - name: Update formula
      run: |
        VERSION=${{ steps.version.outputs.VERSION }}
        DARWIN_ARM64_SHA=${{ steps.fetch-assets.outputs.DARWIN_ARM64_SHA }}
        DARWIN_AMD64_SHA=${{ steps.fetch-assets.outputs.DARWIN_AMD64_SHA }}
        LINUX_ARM64_SHA=${{ steps.fetch-assets.outputs.LINUX_ARM64_SHA }}
        LINUX_AMD64_SHA=${{ steps.fetch-assets.outputs.LINUX_AMD64_SHA }}

        echo ":: Updating the formula file"
        sed -i "s/version \".*\"/version \"$VERSION\"/" Formula/kagent.rb
        sed -i "s/sha256 \".*\" # darwin-arm64/sha256 \"$DARWIN_ARM64_SHA\"/" Formula/kagent.rb
        sed -i "s/sha256 \".*\" # darwin-amd64/sha256 \"$DARWIN_AMD64_SHA\"/" Formula/kagent.rb
        sed -i "s/sha256 \".*\" # linux-arm64/sha256 \"$LINUX_ARM64_SHA\"/" Formula/kagent.rb
        sed -i "s/sha256 \".*\" # linux-amd64/sha256 \"$LINUX_AMD64_SHA\"/" Formula/kagent.rb

        echo ":: Updating README"
        sed -i "s/\*\*v \.\*.\*\*/**v$VERSION**/" README.md

    - name: Commit changes directly to main
      env:
        PAGER: cat
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add Formula/kagent.rb README.md
        git status
        git diff > diff.txt
        cat diff.txt
#        cat Formula/kagent.rb
#        cat README.md
        #git commit -m "Update kagent to ${{ steps.version.outputs.VERSION }}"
        #git push
